### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by ctoLarsson** [MateusZitelli/convert360#1]
Hat off! I am extremely happy to see this initiative! However I get a runtime error. 

I suspect it has to do somehow with the OpenGL Shader version, but after several hours of googling and testing I cannot figure it out. Error message:

-----
anders$ convert360 -i testin.jpg -o testout.jpg -s 300 300
Traceback (most recent call last):
  File "/usr/local/bin/convert360", line 29, in <module>
    args.output_type)
  File "/Users/anders/Library/Python/2.7/lib/python/site-packages/convert360/__init__.py", line 26, in main
    with projector(output_size) as renderer:
  File "/Users/anders/Library/Python/2.7/lib/python/site-packages/convert360/projector.py", line 119, in __init__
    GL.GL_VERTEX_SHADER)
  File "/Users/anders/Library/Python/2.7/lib/python/site-packages/OpenGL/GL/shaders.py", line 226, in compileShader
    shaderType,
RuntimeError: ("Shader compile failure (0): ERROR: 0:2: '' :  version '320' is not supported\nERROR: 0:2: '' : syntax error: #version\nERROR: 0:3: 'precision' : syntax error: syntax error\n", ['\n#version 320 es\nprecision highp float;\nlayout(location = 0) in vec3 position;\nlayout(location = 1) in vec2 texCoord;\nout vec2 texCoordOut;\nvoid main()\n{\n    gl_Position = vec4(position, 1.0);\n    texCoordOut = texCoord;\n} '], GL_VERTEX_SHADER)
-----------

I've tried to update to latest xcode (Version 8.3.3, 8E3004b).
I also ran:  xcode-select --install
I downloaded GLview which shows this, if related:

OpenGL version: 4.1 INTEL-10.25.13
OpenCL platform: OpenCL 1.2 (Apr 4 2017 19:07:42) (FULL_PROFILE)
Metal platform: Features 1v1, 1v2
Mac OS X 10.12.5 (16F73)

------------

Also these are the python versions if relevant. I guess this is what I get with latest xcode:

anders$ python --version
Python 2.7.10
anders$ python3 --version
Python 3.6.1

------------

**Comment by MateusZitelli** [comment]
Hi @andelar, could you check my last commit, I downgraded the required OpenGL version, hopefully that should fix this issue.

**Comment by MateusZitelli** [comment]
I'm reopening the issue, the fix doesn't work on MacOS.

**Comment by MateusZitelli** [comment]
Last commit allows the usage on MacOS, hopefully that should fix your problem, so I'm closing this issue for now.

**Comment by ctoLarsson** [comment]
Hi, once again thank you for your initiative and quick response. Yes it worked! 
Well done!
(For other users: Do you need to upgrade the pip package also? pip install convert360 still points to the old one.)

**Comment by MateusZitelli** [comment]
Yeah sure, just wanted to wait for your confirmation.
